title: Rish - Declarative UI in Unity
email: lisandro@clockworklabs.io
description: >- # this means to ignore newlines until "baseurl:"
  Declarative, element-based UI library for Unity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rish-ui.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
# permalink: /:slug

collections:
  features:
    output: false
  docs:
    output: true
    permalink: /docs/:categories/:title
  auto_docs:
    output: true
    permalink: /docs/:categories/:title


# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md

github_url:  https://github.com/clockworklabs/rish
discord_url: https://discord.gg/hzHGZEGpVa
x_url: https://x.com/clockwork_labs

rish-versions:
  - "3.0.0"

roots-versions:
  - "1.0.0"

rish-roots-pairs:
  "3.0.0": "1.0.0"

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs
      icon-style: solid
  - scope:
      path: ""
      type: auto_docs
      icon-style: solid
    values:
      layout: docs
  - scope:
      path: "_auto_docs/rish"
    values:
      categories:
        - "rish"
  - scope:
      path: "_auto_docs/roots"
    values:
      categories:
        - "roots"
  - scope:
      path: "_docs/rish/3.0.0"
    values:
      categories:
        - "rish"
        - "3.0.0"
  - scope:
      path: "_docs/roots/1.0.0"
    values:
      categories:
        - "roots"
        - "1.0.0"